package com.core.zjqk.model;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import com.common.kits.ReturnMsg;
import com.core.admin.shiro.ShiroUtils;
import com.core.zjqk.model.base.BaseAccount;
import com.google.common.collect.Lists;
import com.jfinal.core.Controller;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvoiceTitle extends BaseAccount<InvoiceTitle> {
	
	public static final InvoiceTitle dao = new InvoiceTitle();
	
	public Page<InvoiceTitle> page(Controller c){
		String classify = ShiroUtils.getClassify();
		String select = "SELECT id,name ";
		StringBuilder sqlExceptSelect = new StringBuilder();
		List<Object> params = Lists.newArrayList();
		sqlExceptSelect.append("FROM invoice_title WHERE flag=1 AND classify='"+classify+"' ");
		String itName = c.getPara("itName");
		if(StringUtils.isNotBlank(itName)){
			sqlExceptSelect.append("AND INSTR(name, ?) ");
			params.add(itName);
	    }
		sqlExceptSelect.append("ORDER BY name ");
		return this.paginate(c.getParaToInt("page"), c.getParaToInt("rows"), select, sqlExceptSelect.toString(), params.toArray());
	}
	
	public List<InvoiceTitle> list(){
		String classify = ShiroUtils.getClassify();
		return this.find("SELECT name AS itName, id AS itId FROM invoice_title WHERE flag=1 AND classify='"+classify+"' ORDER BY name ");
	}
	
	public ReturnMsg saveOrUpdate(Controller c){
		String classify = ShiroUtils.getClassify();
		boolean result = false;
		String id = c.getPara("id");
		String name = c.getPara("name");
		
		/*Long count = this.findFirst("SELECT COUNT(1) AS count FROM invoice_title WHERE name=? AND flag=1 AND classify='"+classify+" ", name).getLong("count");
		if(StringUtils.isBlank(id) && count > 0){
			return ReturnMsg.REPEATERROR;
		}else{
			InvoiceTitle it = new InvoiceTitle();
			it.set("name", name).set("classify", classify);
			result = StringUtils.isNoneBlank(id) ? it.set("id", id).update() : it.save();
		}*/
		
		InvoiceTitle it = new InvoiceTitle();
		it.set("name", name).set("classify", classify);
		result = StringUtils.isNoneBlank(id) ? it.set("id", id).update() : it.save();
		return result ? ReturnMsg.SUCCESS : ReturnMsg.ERROR;
	}
	
	public ReturnMsg deletes(String ids){
		Integer orgId = ShiroUtils.getOrgId();
		if(orgId == 1){
			boolean update = false;
			for (String id : ids.split(";")) {
				update = new InvoiceTitle().set("id", id).set("flag", 2).update();
				if(update == false){
					break;
				}
			}
			return update ? ReturnMsg.SUCCESS : ReturnMsg.ERROR;
		}else{
			return ReturnMsg.NORIGHT;
		}
	}
	
	public Integer findITId(String name){
		String sql = "SELECT id FROM invoice_title WHERE `name`=? AND flag=1 ";
		return this.findFirst(sql, name).get("id");
	}
	
	public ReturnMsg importInvoiceTitles(Controller c) {
		Workbook workbook = null;
		InputStream is = null;
		boolean save = false;
		try {
			is = new FileInputStream(c.getFile().getFile());
			workbook = new XSSFWorkbook(is);
			Sheet sheet = workbook.getSheetAt(0);
			Row row = null;
			String[] fields = {"name","classify"};
			for (int i = 1; i <= sheet.getLastRowNum(); i++) {
				row = sheet.getRow(i);
				if(row != null){
					InvoiceTitle it = new InvoiceTitle();
					for (int j = 0; j < fields.length; j++) {
						Cell cell = row.getCell(j);
						if(cell != null){
							it.set(fields[j], cell.toString().trim());
						}else{
							continue;
						}
					}
					save = it.save();
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				is.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return save ? ReturnMsg.SUCCESS : ReturnMsg.ERROR;
	}
}
