package com.core.zjqk.model;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import com.common.kits.ReturnMsg;
import com.core.admin.shiro.ShiroUtils;
import com.core.zjqk.model.base.BasePayAccount;
import com.google.common.collect.Lists;
import com.jfinal.core.Controller;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayAccount extends BasePayAccount<PayAccount> {
	public static final PayAccount dao = new PayAccount();
	
	public Page<PayAccount> page(Controller c){
		String classify = ShiroUtils.getClassify();
		String select = "SELECT id, name, account, bank ";
		StringBuilder sqlExceptSelect = new StringBuilder();
		List<Object> params = Lists.newArrayList();
		sqlExceptSelect.append("FROM pay_account WHERE del_flag=1 AND classify='"+classify+"' ");
		String paName = c.getPara("paName");
		if(StringUtils.isNotBlank(paName)){
			sqlExceptSelect.append("AND INSTR(name, ?) ");
			params.add(paName);
	    }
		sqlExceptSelect.append("ORDER BY name ");
		return this.paginate(c.getParaToInt("page"), c.getParaToInt("rows"), select, sqlExceptSelect.toString(), params.toArray());
	}
	
	public List<PayAccount> list(){
		String classify = ShiroUtils.getClassify();
		return this.find("SELECT name AS paName, id AS paId FROM pay_account WHERE del_flag=1 AND classify='"+classify+"' ORDER BY name ");
	}
	
	public ReturnMsg saveOrUpdate(Controller c){
		String classify = ShiroUtils.getClassify();
		boolean result = false;
		String id = c.getPara("id");
		String name = c.getPara("name");
		if(StringUtils.isBlank(name)){
			return ReturnMsg.DATAERROR;
		}
		
		/*Long count = this.findFirst("SELECT COUNT(1) AS count FROM pay_account WHERE name=? AND del_flag = 1 AND classify='"+classify+"' ", name).getLong("count");
		if(StringUtils.isBlank(id) && count > 0){
			return ReturnMsg.REPEATERROR;
		}else{
			PayAccount pa = new PayAccount();
			pa.set("name", name)
				.set("account", c.getPara("account"))
				.set("classify", classify)
				.set("bank", c.getPara("bank"))
				.set("trans_num", c.getPara("transNum"))
				.set("invoice_flag", c.getPara("invoiceFlag"));
			result = StringUtils.isNoneBlank(id) ? pa.set("id", id).update() : pa.save();
		}*/
		
		PayAccount pa = new PayAccount();
		pa.set("name", name)
			.set("account", c.getPara("account"))
			.set("classify", classify)
			.set("bank", c.getPara("bank"))
			.set("trans_num", c.getPara("transNum"))
			.set("invoice_flag", c.getPara("invoiceFlag"));
		result = StringUtils.isNoneBlank(id) ? pa.set("id", id).update() : pa.save();
		return result ? ReturnMsg.SUCCESS : ReturnMsg.ERROR;
	}
	
	public ReturnMsg deletes(String ids){
		Integer orgId = ShiroUtils.getOrgId();
		if(orgId == 1){
			boolean update = false;
			for (String id : ids.split(";")) {
				update = new PayAccount().set("id", id).set("del_flag", 2).update();
				if(update == false){
					break;
				}
			}
			return update ? ReturnMsg.SUCCESS : ReturnMsg.ERROR;
		}else{
			return ReturnMsg.NORIGHT;
		}
	}
	
	public Integer findPayAccountId(String name){
		String sql = "SELECT id FROM pay_account WHERE INSTR(name, ?) AND del_flag=1 ";
		return this.findFirst(sql, name).get("id");
	}
	
	public ReturnMsg importPayAccounts(Controller c) {
		Workbook workbook = null;
		InputStream is = null;
		boolean result = false;
		try {
			is = new FileInputStream(c.getFile().getFile());
			workbook = new XSSFWorkbook(is);
			Sheet sheet = workbook.getSheetAt(0);
			Row row = null;
			String[] fields = {"name","account","bank","classify"};
			for (int i = 1; i <= sheet.getLastRowNum(); i++) {
				row = sheet.getRow(i);
				if(row != null){
					PayAccount pa = new PayAccount();
					for (int j = 0; j < fields.length; j++) {
						Cell cell = row.getCell(j);
						if(cell != null){
							pa.set(fields[j], cell.toString().trim());
						}else{
							continue;
						}
					}
					result = pa.save();
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				is.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return result ? ReturnMsg.SUCCESS : ReturnMsg.ERROR;
	}
}
