package com.core.zjqk.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRentBill<M extends BaseRentBill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setYmDate(java.lang.String ymDate) {
		set("ym_date", ymDate);
	}

	public java.lang.String getYmDate() {
		return get("ym_date");
	}

	public void setActualIncome(java.lang.Double actualIncome) {
		set("actual_income", actualIncome);
	}

	public java.lang.Double getActualIncome() {
		return get("actual_income");
	}

	public void setShopIncome(java.lang.Double shopIncome) {
		set("shop_income", shopIncome);
	}

	public java.lang.Double getShopIncome() {
		return get("shop_income");
	}

	public void setActualPayment(java.lang.Double actualPayment) {
		set("actual_payment", actualPayment);
	}

	public java.lang.Double getActualPayment() {
		return get("actual_payment");
	}
	
	public void setBdzj(java.lang.Double bdzj) {
		set("bdzj", bdzj);
	}
	
	public java.lang.Double getBdzj() {
		return get("bdzj");
	}
	
	public void setTcbl(java.lang.String tcbl) {
		set("tcbl", tcbl);
	}

	public java.lang.String getTcbl() {
		return get("tcbl");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setPayableFee(java.lang.Double payableFee) {
		set("payable_fee", payableFee);
	}

	public java.lang.Double getPayableFee() {
		return get("payable_fee");
	}

	public void setDifferenceFee(java.lang.Double differenceFee) {
		set("difference_fee", differenceFee);
	}

	public java.lang.Double getDifferenceFee() {
		return get("difference_fee");
	}

}
