package com.core.zjqk.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDispDetails<M extends BaseDispDetails<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBillNo(java.lang.String billNo) {
		set("bill_no", billNo);
	}

	public java.lang.String getBillNo() {
		return get("bill_no");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}
	
	public void setDId(java.lang.Integer dId) {
		set("d_id", dId);
	}
	
	public java.lang.Integer getDId() {
		return get("d_id");
	}

	public void setMoney(java.lang.Double money) {
		set("money", money);
	}

	public java.lang.Double getMoney() {
		return get("money");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}
}
