package com.core.zjqk.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCycBills<M extends BaseCycBills<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setAId(java.lang.Integer aId) {
		set("a_id", aId);
	}

	public java.lang.Integer getAId() {
		return get("a_id");
	}

	public void setPId(java.lang.Integer pId) {
		set("p_id", pId);
	}

	public java.lang.Integer getPId() {
		return get("p_id");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setBillNo(java.lang.String billNo) {
		set("bill_no", billNo);
	}

	public java.lang.String getBillNo() {
		return get("bill_no");
	}

	public void setPayDate(java.lang.String payDate) {
		set("pay_date", payDate);
	}

	public java.lang.String getPayDate() {
		return get("pay_date");
	}

	public void setActualMoney(java.lang.Double actualMoney) {
		set("actual_money", actualMoney);
	}

	public java.lang.Double getActualMoney() {
		return get("actual_money");
	}

	public void setActualDate(java.lang.String actualDate) {
		set("actual_date", actualDate);
	}

	public java.lang.String getActualDate() {
		return get("actual_date");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}
	
	public void setLb(java.lang.String lb) {
		set("lb", lb);
	}

	public java.lang.String getLb() {
		return get("lb");
	}
	
	public void setZdr(java.lang.String zdr) {
		set("zdr", zdr);
	}
	
	public java.lang.String getZdr() {
		return get("zdr");
	}
	
	public void setSpr(java.lang.String spr) {
		set("spr", spr);
	}
	
	public java.lang.String getSpr() {
		return get("spr");
	}
	
	public void setSprq(java.lang.String spr) {
		set("spr", spr);
	}
	
	public java.lang.String getSprq() {
		return get("spr");
	}

	public void setYm(java.lang.String ym) {
		set("ym", ym);
	}

	public java.lang.String getYm() {
		return get("ym");
	}
	
}
