package com.core.zjqk.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayAccount<M extends BasePayAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public void setTransNum(java.lang.String transNum) {
		set("trans_num", transNum);
	}

	public java.lang.String getTransNum() {
		return get("trans_num");
	}

	public void setInvoiceFlag(java.lang.Integer invoiceFlag) {
		set("invoice_flag", invoiceFlag);
	}

	public java.lang.Integer getInvoiceFlag() {
		return get("invoice_flag");
	}

	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

	public java.lang.Integer getDelFlag() {
		return get("del_flag");
	}

	public void setClassify(java.lang.String classify) {
		set("classify", classify);
	}
	
	public java.lang.String getClassify() {
		return get("classify");
	}
}
