package com.core.zjqk.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAreas(java.lang.String areas) {
		set("areas", areas);
	}

	public java.lang.String getAreas() {
		return get("areas");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return get("brand");
	}

	public void setPaymentDay(java.lang.Integer paymentDay) {
		set("payment_day", paymentDay);
	}

	public java.lang.Integer getPaymentDay() {
		return get("payment_day");
	}

	public void setBerthNo(java.lang.String berthNo) {
		set("berth_no", berthNo);
	}

	public java.lang.String getBerthNo() {
		return get("berth_no");
	}

	public void setOpeningDate(java.lang.String openingDate) {
		set("opening_date", openingDate);
	}

	public java.lang.String getOpeningDate() {
		return get("opening_date");
	}

	public void setCloseDate(java.lang.String closeDate) {
		set("close_date", closeDate);
	}

	public java.lang.String getCloseDate() {
		return get("close_date");
	}

	public void setContractSubject(java.lang.String contractSubject) {
		set("contract_subject", contractSubject);
	}

	public java.lang.String getContractSubject() {
		return get("contract_subject");
	}

	public void setContractStime(java.lang.String contractStime) {
		set("contract_stime", contractStime);
	}

	public java.lang.String getContractStime() {
		return get("contract_stime");
	}

	public void setContractEtime(java.lang.String contractEtime) {
		set("contract_etime", contractEtime);
	}

	public java.lang.String getContractEtime() {
		return get("contract_etime");
	}

	public void setFreeRentStime(java.lang.String freeRentStime) {
		set("free_rent_stime", freeRentStime);
	}

	public java.lang.String getFreeRentStime() {
		return get("free_rent_stime");
	}

	public void setFreeRentEtime(java.lang.String freeRentEtime) {
		set("free_rent_etime", freeRentEtime);
	}

	public java.lang.String getFreeRentEtime() {
		return get("free_rent_etime");
	}

	public void setFinanceContact(java.lang.String financeContact) {
		set("finance_contact", financeContact);
	}

	public java.lang.String getFinanceContact() {
		return get("finance_contact");
	}

	public void setOperationContact(java.lang.String operationContact) {
		set("operation_contact", operationContact);
	}

	public java.lang.String getOperationContact() {
		return get("operation_contact");
	}
	
	public void setClassify(java.lang.String classify) {
		set("classify", classify);
	}
	
	public java.lang.String getClassify() {
		return get("classify");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

}
